### ISSUE TITLE
Hunk #1 FAILED at 20

### ISSUE THREAD

**Issue by orlfman** [Fincer/openra-tibsunra2#7]
```
Cloning into 'ra2'...
done.
==> Starting pkgver()...
==> Starting build()...
patching file mods/all/mod.yaml
Hunk #1 FAILED at 20.
1 out of 1 hunk FAILED -- saving rejects to file mods/all/mod.yaml.rej
patching file mods/ra2/mod.yaml
Hunk #1 succeeded at 5 with fuzz 1.
patching file utility.cmd
==> ERROR: A failure occurred in build().
    Aborting...
rm: cannot remove './*.orig': No such file or directory

Whoops! Something went wrong. Please check possible error messages above.
```
i tried both option 1 and 2 (manual and auto) and it fails both times with the same error. also, if i do manual, that means i can install openra-git from the AUR?

**Comment by LinuxDonald** [comment]
i think its because of https://github.com/OpenRA/OpenRA/commit/709e2a26e13b614f9a240734fd54a09e74eb6778

@Fincer must fix that then it should work again :)

**Comment by LinuxDonald** [comment]
i think the patches here need an rebase?

**Comment by Fincer** [comment]
Yeah, I'm working on it. Outdated patches & scripts are the main reason for the issue.

**Comment by Fincer** [comment]
Fix will be released very soon (within a few hours) so the script will run again. I'm doing some last minute testing now.

**Comment by Fincer** [comment]
Should be fixed now. Closing.
